version: '3.8'

services:
  payment_db:
    image: postgres:15
    container_name: payments-db
    environment:
      POSTGRES_DB: payments_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - payments_db_data:/var/lib/postgresql/data
    networks:
      - payments-network

volumes:
  payments_db_data:

networks:
  payments-network:
    driver: bridge